[package]
name = "parse-monitors"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colorous = "1.0.5"
csv = "1.1.6"
plotters = "0.3.1"
regex = "1.5.4"
structopt = "0.3.21"
