[package]
name = "parse-monitors"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bzip2 = "0.4.3"
colorous = "1.0.5"
csv = "1.1.6"
indicatif = "0.16.2"
nalgebra = { version = "0.27.1", features = ["rand"] }
plotters = "0.3.1"
regex = "1.5.4"
serde = { version = "1.0.126", features = ["derive"] }
structopt = "0.3.21"
windloading = { git = "https://github.com/rconan/windloading.git", branch = "ns-opm-im" }
serde-pickle = "0.6.3"

[dev-dependencies]
rand = "0.8.4"
